version: 2.1
executors:
  github-testing:
    docker:
      - image: furetur/plugin-utilities:github-testing

jobs:
  build:
    executor: github-testing
    working_directory: /repo
    steps:
      - checkout
      - run:
          name: Check ANDROID_HOME folder
          command: cd $ANDROID_HOME && ls
      - run:
          name: Download Projects
          command: |
            ./gradlew downloadRepos \
            -Prepos=/repo/plugin-utilities-plugin/src/test/resources/javaGithubRepositories.yaml \
            -Poutput=$JAVA_GITHUB_PROJECTS
      - run:
          name: Preprocess Projects
          command: |
            ./gradlew preprocessKotlinJava \
            -Pinput=$JAVA_GITHUB_PROJECTS \
            -Poutput=/preprocessed \
            -PandroidSdk=$ANDROID_HOME
      - run:
          name: Open Projects
          command: ./gradlew testOpenKotlinJava -Pinput=/preprocessed
      - store_artifacts:
          path: /repo/plugin-utilities-plugin/build/idea-sandbox/system/log/idea.log

