name: build

on: [push]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Setup Java 11 environment for the next steps
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 11

      # Cache Gradle dependencies
      # Cache Gradle Wrapper
      - name: Cache Gradle dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-



  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
    
      # Setup Java 11 environment for the next steps
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 11
    
      - uses: actions/checkout@v2
      - run: ./gradlew build
      
      - name: Upload Test Report
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: test-report
          path: |
            build/reports/tests/**/*


  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      # Setup Java 11 environment for the next steps
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: actions/checkout@v2
      - name: Run tests
        run: ./gradlew test


  code-style:
    needs: build
    runs-on: ubuntu-latest
    steps:
      # Setup Java 11 environment for the next steps
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: actions/checkout@v2
      - run: ./gradlew ktlintCheck

  open-java-mocks:
    needs: build
    runs-on: ubuntu-latest
    steps:
      # Setup Java 11 environment for the next steps
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: actions/checkout@v2
      # Download & install the Android SDK.
      - uses: malinskiy/action-android/install-sdk@release/0.1.2
      # Set up platform tools like adb.
      - run: sdkmanager platform-tools
      # Open mock Java projects
      - run: ./gradlew androidCli -Prunner="testOpenJava" -Pinput="$GITHUB_WORKSPACE/plugin-utilities-plugin/src/test/resources/org/jetbrains/research/pluginUtilities/java_mock_projects" -PpreprocessOutput="~/preprocessed_projects" -PandroidSdk="$ANDROID_HOME"
