name: test on projects

on:
  push:
    branches:
      - main
      - github-testing
  workflow_dispatch: {}


jobs:
  setup:
    runs-on: ubuntu-latest
    container: furetur/plugin-utilities:github-testing
    steps:
      - uses: actions/checkout@v2

      # Cache Gradle dependencies
      # Cache Gradle Wrapper
      - name: Cache Gradle dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-



  open-java-mocks:
    needs: setup
    runs-on: ubuntu-latest
    container: furetur/plugin-utilities:github-testing
    steps:
      - uses: actions/checkout@v2

      - name: Open Mock Projects
        run: |
          ./gradlew testOpenKotlinJava \
            -Pinput="$JAVA_MOCK_PROJECTS" \
            -PpreprocessOutput="$GITHUB_WORKSPACE/plugin-utilities-plugin/build/preprocessed-projects" \
            -PandroidSdk="$ANDROID_HOME"
      # Upload IDEA logs
      - uses: actions/upload-artifact@v2
        name: Upload IDEA Logs
        if: always()
        with:
          name: Idea Logs
          path: plugin-utilities-plugin/build/idea-sandbox/system/log/idea.log



  open-java-github-projects:
    needs: setup
    runs-on: ubuntu-latest
    container: furetur/plugin-utilities:github-testing
    steps:
      - uses: actions/checkout@v2

      - name: Open Java Projects
        run: |
          ./gradlew testOpenKotlinJava \
            -Pinput="$JAVA_GITHUB_PROJECTS" \
            -PpreprocessOutput="~/preprocessed_projects" \
            -PandroidSdk="$ANDROID_HOME"

      # Upload IDEA logs
      - uses: actions/upload-artifact@v2
        name: Upload IDEA Logs
        if: always()
        with:
          name: Idea Logs
          path: plugin-utilities-plugin/build/idea-sandbox/system/log/idea.log

  open-java-github-projects-simple:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Download Java Projects from Github
        run: ./gradlew downloadRepos -Prepos=$GITHUB_WORKSPACE/plugin-utilities-plugin/src/test/resources/javaGithubRepositories.yaml -Poutput=$GITHUB_WORKSPACE/build/javaGithubRepos
      - name: Open Java Projects
        run: ./gradlew testOpenKotlinJava -Pinput=$GITHUB_WORKSPACE/build/javaGithubRepos -PpreprocessOutput=~/preprocessed_projects -PandroidSdk=$ANDROID_HOME
      # Upload IDEA logs
      - uses: actions/upload-artifact@v2
        name: Upload IDEA Logs
        if: always()
        with:
          name: Idea Logs Simple
          path: plugin-utilities-plugin/build/idea-sandbox/system/log/idea.log
